DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid WHERE c.relname='users' AND a.attname='id' AND a.attidentity <> '') THEN ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid WHERE c.relname='clients' AND a.attname='id' AND a.attidentity <> '') THEN ALTER TABLE clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid WHERE c.relname='projects' AND a.attname='id' AND a.attidentity <> '') THEN ALTER TABLE projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; END IF;
END $$;
